# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7b2e4aeb6c434d36917c4d929c13105293bda7f8b2350d0af4cbdfb0d945da72dedd5b9fb49f22055ae030dfcbf4531b0304f479b8be379d992767fcc0e2803

test:
  secret_key_base: ce638c7e011456e21da1ae62e9f32ad5dd51ae46816e0f98603db7b393beb8324d3b0ee8d9ee127d2ae8e28f8b9db490a21f750a911c7cf65de2a060c2cb47ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
